-version: '3.8'
services:
  campusxchange-api:
    container_name: campusxchange-api
    image: campusxchange/campusxchange-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/campusxchange
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres-db

  campusxchange-ui:
    container_name: campusxchange-ui
    build:
      context: ./campusxchange-ui
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://campusxchange-api:8080
    ports:
      - "3000:80" # Serve React on port 3000 through Nginx
    restart: always
    depends_on:
      - campusxchange-api