name: Build Campusxchange Backend
on:
  push:
    paths:
      - "campusxchange/**"
    branches: ["develop"]
  pull_request:
    paths:
      - "campusxchange/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-campusxchange-api:
    name: Build Campusxchange api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./campusxchange
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Set execute permission for mvnw
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image
        run : |
          echo "Pushing the image to Docker Hub..."
